[package]
name = "tvt-tu-vi-dau-so-app"
version = "1.1.0"
description = "T&T Tu Vi Dau So App (T&T Hoang Gia Royal)"
authors = ["T&T Hoang Gia Royal"]
edition = "2021"

[lib]
name = "tvt_tu_vi_dau_so_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
